repos:
  # Markdown linting
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.12.1
    hooks:
      - id: markdownlint-cli2
  # Python linting and formatting
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.2.1
    hooks:
      # Run the linter.
      - id: ruff
        # Enable automatic fixing of issues
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
  # Python documentation linting
  - repo: https://github.com/jsh9/pydoclint
    rev: 0.4.0
    hooks:
      - id: pydoclint
        args: [--style=google]
  # Python type checking
  # TODO: Config to avoid false confidence.
  #       See: https://jaredkhan.com/blog/mypy-pre-commit
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.8.0"
    hooks:
      - id: mypy
        args: []
  # Code spell checking
  # TODO: Config dictionaries to reduce false positives
  #       See: https://github.com/streetsidesoftware/cspell-cli?tab=readme-ov-file#setup-custom-dictionary
  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v8.4.0
    hooks:
      - id: cspell
  # Shell linting
  - repo: https://github.com/koalaman/shellcheck-precommit
    rev: v0.7.2
    hooks:
      - id: shellcheck
  # Shell formatting
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.8.0-1
    hooks:
      - id: shfmt
  # Docker linting
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.0
    hooks:
      - id: hadolint-docker

